stages:
  - test
  - package
  - deploy

test:
  stage: test
  image: python:3
  before_script:
    - pip install -r requirements.txt -r requirements-test.txt
  script:
    - python -m unittest discover -s tests/

package:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

deploy-test:
  stage: deploy
  image: alpine/helm:3.4.2
  when: manual
  environment:
    name: test
    kubernetes:
      namespace: search-engine
  script:
    - helm upgrade --namespace search-engine --create-namespace --install ui ./chart --set image.repository=$CI_REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHORT_SHA,mongo.url=$MONGO_URL

deploy-prod:
  stage: deploy
  image: alpine/helm:3.4.2
  when: manual
  environment:
    name: production
    kubernetes:
      namespace: search-engine
  script:
    - helm upgrade --namespace search-engine --create-namespace --install ui ./chart --set image.repository=$CI_REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHORT_SHA,mongo.url=$MONGO_URL